package routes

import (
	"backend_jamu/controllers"
	_ "backend_jamu/docs" // generated by swag
	"backend_jamu/middleware"
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger"
)

func SetupRoutes() *http.ServeMux {
	mux := http.NewServeMux()

	// Swagger UI
	mux.Handle("/swagger/", httpSwagger.WrapHandler)

	// Inisialisasi Controller
	authCtrl := &controllers.AuthController{}
	productCtrl := &controllers.ProductController{}
	newsCtrl := &controllers.NewsController{}

	// --- Public Routes ---
	mux.HandleFunc("/api/login", authCtrl.Login)

	// API Products (GET is Public)
	mux.Handle("/api/products", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			productCtrl.GetAll(w, r)
		case http.MethodPost:
			middleware.AuthMiddleware(middleware.AdminOnly(http.HandlerFunc(productCtrl.Create))).ServeHTTP(w, r)
		case http.MethodPut:
			middleware.AuthMiddleware(middleware.AdminOnly(http.HandlerFunc(productCtrl.Update))).ServeHTTP(w, r)
		case http.MethodDelete:
			middleware.AuthMiddleware(middleware.AdminOnly(http.HandlerFunc(productCtrl.Delete))).ServeHTTP(w, r)
		default:
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	}))

	// API News (GET is Public)
	mux.Handle("/api/news", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			newsCtrl.GetAll(w, r)
		case http.MethodPost:
			middleware.AuthMiddleware(middleware.AdminOnly(http.HandlerFunc(newsCtrl.Create))).ServeHTTP(w, r)
		case http.MethodPut:
			middleware.AuthMiddleware(middleware.AdminOnly(http.HandlerFunc(newsCtrl.Update))).ServeHTTP(w, r)
		case http.MethodDelete:
			middleware.AuthMiddleware(middleware.AdminOnly(http.HandlerFunc(newsCtrl.Delete))).ServeHTTP(w, r)
		default:
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	}))

	return mux
}
